### ISSUE TITLE
KeepInv Broken?

### ISSUE THREAD

**Issue by KlutchWhiskey** [Logics4/IndividualKeepInventory#1]
So I intiated the command for a user to test and it worked but then I set the value to false and they still have keepinv and when trying to add to other users they have values set to true but it is not working? Any work around?

**Comment by Logics4** [comment]
Please state your current setup (output of `/version` and output of `/plugins`).

Please make sure that the `keepInventory` gamerule is set to false (`/gamerule keepInventory false`).

The code of this plugin is as simple as it can be - the plugin just purely checks if the player has the required permission through the method available in Bukkit API (`Player#hasPermission()`). It most likely has to be with your permissions setup. Make sure you did not give the IndividualKeepInventory permission to the default group, or any group in which your players may be.

**Comment by Logics4** [comment]
I will close this issue due to inactivity, as I could not reproduce the issue myself. If you still suffer from it, though, feel free to comment and I will reopen it.
